### PR TITLE
Fix: Reference CSV Column Name rather than Number, Add Check

### LINKED ISSUE #169: "RemovedCACertificateReportCSVFormat" file format has changed
Hi,

The number of columns in the CSV file "RemovedCACertificateReportCSVFormat" (https://ccadb-public.secure.force.com/mozilla/RemovedCACertificateReportCSVFormat) appears to have changed, and this is causing an error when executing the "inspect" command.

**internal/analyse/analyse.go**

```go
func downloadMozillaRemovedCACertsList() ([]removedCertificate, error) {
        const mozillaRemovedCACertificateReportURL = "https://ccadb-public.secure.force.com/mozilla/RemovedCACertificateReportCSVFormat"

        resp, err := http.Get(mozillaRemovedCACertificateReportURL)
        if err != nil {
                return nil, err
        }
        csvReader := csv.NewReader(resp.Body)
        csvLines, err := csvReader.ReadAll()
        if err != nil {
                return nil, err
        }

        removedCerts := make([]removedCertificate, len(csvLines))
        for i, csvLine := range csvLines {
                removedCerts[i] = removedCertificate{
                        // From the CSV format that Mozilla publishes, the 8th column (id 7) is the fingerprint and the 23rd column
                        // (id 22) is the comment.
                        Fingerprint: csvLine[7],
 ->                     Comments:    csvLine[22],
                }
        }
        return removedCerts, nil
}
```

```bash
$ paranoia inspect file://image.tar
panic: runtime error: index out of range [22] with length 21
goroutine 1 [running]:
github.com/jetstack/paranoia/internal/analyse.downloadMozillaRemovedCACertsList()
	/home/runner/work/paranoia/paranoia/internal/analyse/analyse.go:67 +0x2bf
github.com/jetstack/paranoia/internal/analyse.NewAnalyser(...)
	/home/runner/work/paranoia/paranoia/internal/analyse/analyse.go:41
github.com/jetstack/paranoia/cmd.newInspect.func2(0xc000136608?, {0xc00013a1c0?, 0x1?, 0x1?})
	/home/runner/work/paranoia/paranoia/cmd/inspect.go:49 +0xb6
github.com/spf13/cobra.(*Command).execute(0xc000136608, {0xc00013a180, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000136008)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/jetstack/paranoia/cmd.Execute()
	/home/runner/work/paranoia/paranoia/cmd/root.go:71 +0x1d
main.main()
	/home/runner/work/paranoia/paranoia/main.go:8 +0xf
```

The code is looking for column 23 to retrieve the comment, but that column no longer seems to exist in the new files. It appears the comment is now in column 21.

Instead of hard-coding the column index, maybe we should specify the name of the column to retrieve.

### PR DESCRIPTION
**Pull request by joshw123**
Mozilla have changed the format of the CSV File, Rather than referencing the line directly, we should lookup by the Column name to prevent this happening again, A check has also been added to prevent go panics. 

Resolves #169

### CODE REVIEW

File: internal/analyse/analyse.go [hunk 1]
```diff
@@ -60,11 +60,36 @@ func downloadMozillaRemovedCACertsList() ([]removedCertificate, error) {
...
+				}
+			}
+
+			if fingerprint == -1 {
+				return nil, fmt.Errorf("required column 'SHA-256 Fingerprint' not found in CSV header")
+			}
+			if comments == -1 {
+				return nil, fmt.Errorf("required column 'Comments' not found in CSV header")
+			}
+		}
```
Comment (davidcollom) [inline internal/analyse/analyse.go:88]: Wouldn't this make more sense being done outside of the loop? as in - only once - as validation of the headers? 

You could move over to the "Read" and only load in the first row (headers) check that, then the main logic of fingerprint/comment indexes is a little cleaner?

nit: use constants for the case statements so it's easier to update in the future?
